"""course_date,enrollment追加

Revision ID: a59f6b2cbe9a
Revises: d3a0f6509799
Create Date: 2026-04-19 04:55:55.084279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59f6b2cbe9a'
down_revision: Union[str, Sequence[str], None] = 'd3a0f6509799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###